# Generated by Django 6.0.4 on 2026-04-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.CharField(blank=True, choices=[('origin', 'Origin'), ('destination', 'Destination'), ('intermediate', 'Intermediate')], max_length=20, null=True),
        ),
    ]
