# Generated by Django 6.0.4 on 2026-04-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint', '0002_waypoint_waypoint_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='waypoint_type',
        ),
    ]
