# Generated by Django 6.0.4 on 2026-04-27 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_stop_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('rest_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stop', to='rest_stop_planner.reststop')),
            ],
        ),
    ]
