# Generated by Django 6.0.4 on 2026-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateset',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinateset',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
