# Generated by Django 6.0.4 on 2026-04-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route_planner', '0002_delete_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=255)),
                ('location_type', models.CharField(blank=True, max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='route_planner.trip')),
            ],
        ),
    ]
