# Generated by Django 6.0.4 on 2026-04-28 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waypoint', '0003_remove_waypoint_waypoint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.TextField(blank=True, null=True)),
                ('total_distance_meters', models.IntegerField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='waypoint.waypoint')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='waypoint.waypoint')),
            ],
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waypoint.waypoint')),
            ],
        ),
    ]
