# Generated by Django 6.0.4 on 2026-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_total_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='routewaypoint',
            name='waypoint_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
