# Generated by Django 6.0.4 on 2026-04-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
